language: bash

before_script:
  - sudo pip install Sphinx
  - sudo pip install sphinxcontrib-packages
  - sudo pip install git+git://github.com/SuperKogito/sphinxcontrib-pdfembed
  - sudo pip install sphinx_bootstrap_theme
  - sudo pip install -U ablog
  - sudo pip install sphinxcontrib-napoleon
  - sudo pip install sphinx-sitemap
  - cd _project/docs/

script:
  - ./quickBuild.sh

branches:
  only:
    - master

notifications:
  email: false
    
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true  
  on:
    branch: master
  repo: SuperKogito/SuperKogito.github.io
  target_branch: master
