language: bash
  
before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo apt-get install python-enchant
  - sudo apt-get update
  - sudo pip3 install Sphinx
  - sudo pip3 install sphinxcontrib-packages
  - sudo pip3 install git+git://github.com/SuperKogito/sphinxcontrib-pdfembed
  - sudo pip3 install sphinxcontrib-googleanalytics
  - sudo pip3 install sphinxjp.themes.basicstrap
  - sudo pip3 install sphinx_bootstrap_theme
  - sudo pip3 install sphinxcontrib-spelling
  - sudo pip3 install sphinxcontrib-bibtex
  - sudo pip3 install -U ablog
  - sudo pip3 install sphinxcontrib-napoleon
  - sudo pip3 install sphinx-sitemap
  - sudo pip3 install git+git://github.com/SuperKogito/sphinx-contrib.git
  - cd _project/docs/

script:
  - ./quickBuild.sh

branches:
  only:
    - master

notifications:
  email: false
    
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true  
  on:
    branch: master
  repo: SuperKogito/SuperKogito.github.io
  target_branch: master
