language: bash

before_script:
  - npm install -g gulp
  - npm install
  - cd _project/docs/

script:
  - ./quickBuild.sh

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
