language: ruby
cache: bundler
branches:
  only:
  - master
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
