#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import datetime
sys.path.insert(0, os.path.abspath('../../'))
#sys.path.append(os.path.abspath("_extensions"))

# print(sys.path)
#
def setup(app):
    app.add_stylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')
    app.add_stylesheet("css/custom_style.css")
    #app.add_stylesheet('css/code_style.css')
    #app.add_stylesheet('css/tree_graph.css')

# # Activate the theme.
# sys.path.append(os.path.abspath('_themes'))
# html_theme_path = ['_themes']
# html_theme = 'bootstrap'

# Optional. Use a shorter name to conserve nav. bar space.
html_short_title = 'Ayoub Malek\'s Blog'

# -- Project information -----------------------------------------------------
now = datetime.datetime.now()
project = 'Ayoub Malek'
copyright =  str(now.year) + ', Ayoub Malek'
author = 'SuperKogito'
html_favicon = '_static/favicon.ico'
# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
#    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinxcontrib.napoleon',
    'sphinxjp.themes.basicstrap',
    'sphinxcontrib.googleanalytics',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.spelling',
#    'sphinxcontrib.email',
    'sphinx_sitemap',
    'ablog',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.pdfembed',
]
     #'sphinxprettysearchresults',
    #'sphinxcontrib.disqus',
# 2. Add ablog templates path
import ablog

html_theme = 'alabaster'
templates_path = [ablog.get_html_templates_path()]
print(templates_path)
googleanalytics_id = 'UA-133660046-1'
spelling_lang='en_US'
spelling_show_suggestions=True
night_light_mode_id=True

# add templates path
templates_path = ['_templates']


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'
html_sidebars = { '**': [] }

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []


# -- Options for HTML output ----------------------------------------	both modified:   ../../searchindex.js

source_suffix = '.rst'
master_doc    = 'index'
exclude_patterns = ['_build', 'README.rst']
pygments_style   = 'tango'
html_show_copyright = True

# html_favicon = "favicon.ico"
project = "Ayoub Malek's blog"
html_title = project
suppress_warnings = ["image.nonlocal_uri"]


html_theme_options = {
    # Disable showing the sidebar. Defaults to 'false'
    'nosidebar': True,
}


# Fit in the navbar at the height of image is 37 px.
#html_logo = '../html_logo.png'

# Add any paths that contain custom static files
html_static_path = ['_static']

# html_sidebars = {}
# html_js_files = ['js/mode-switcher.js',]


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SphinxTutorialdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SphinxTutorial.tex', 'SphinxTutorial Documentation',
     'SuperKogito', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
man_pages = [
    (master_doc, 'sphinxtutorial', 'SphinxTutorial Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SphinxTutorial', 'SphinxTutorial Documentation',
     author, 'SphinxTutorial', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------
# -- Options for todo extension ----------------------------------------------
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
site_url = 'https://superkogito.github.io/'

html_show_sourcelink = False
